In [38]:
import numpy as np
seed=42069
np.random.seed(seed)
from sklearn.decomposition import PCA, NMF
from sklearn.datasets import make_blobs
import sys
from scipy import sparse
from matplotlib import pyplot as plt

np.set_printoptions(precision=2, suppress=True)

A, y = make_blobs(n_samples=12, n_features=6)
A = abs(A / A.max()) * 6
A = A.astype(int)
B = np.array([[2,5,2,3,6,1]])

P = NMF(5)
X = P.fit_transform(A)

print(A)

XB = P.transform(B)
print(P.inverse_transform(XB))

[[5 1 4 2 1 2]
 [5 0 4 2 2 3]
 [2 5 2 3 6 1]
 [4 0 4 2 2 2]
 [5 0 4 2 2 3]
 [1 4 2 3 5 1]
 [0 1 0 1 3 0]
 [0 1 0 1 1 0]
 [0 0 0 2 2 1]
 [2 4 1 4 5 2]
 [1 1 0 1 2 0]
 [2 6 1 4 5 2]]
[[2.02 4.99 2.   3.07 5.98 0.92]]
